export const AUTH_ACCESS_SERCRET_KEY = "ACCESS_ALOXE_SECRET";
export const AUTH_REFRESH_SERCRET_KEY = "REFRESH_ALOXE_SECRET";
export const ACCESS_TOKEN_EXPIRY_ON_SECOND = 60 * 5; // 5 minutes
export const REFRESH_TOKEN_EXPIRY_ON_SECOND = 60 * 60 * 24 * 7; // 7 days